[package]
name = "rips"
version = "0.3.0"
authors = ["Jacob Brown <kardeiz@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
categories = ["multimedia::images"]
description = "Rust bindings for libvips"
keywords = ["vips", "libvips"]
readme = "README.md"
repository = "https://github.com/kardeiz/rips"

[dependencies]
libc = { version = "0.2.62", optional = true }

[build-dependencies]
pkg-config = { version = "0.3.16", optional = true }
bindgen = { version = "0.69", optional = true }

[features]
jp2k = ["libc", "pkg-config", "bindgen"]
docs-rs = []

[package.metadata.docs.rs]
features = ["docs-rs"]
