[package]
name = "pulsedcm-commands-view"
authors = ["Antonin Chafiol <antonin.chafiol@gmail.com"]
version = "0.4.1"
description = "Converting DICOM files into PNG"
edition = "2021"

[dependencies]
pulsedcm-core = { path = "../../core" }
rayon = "1.10.0"
tempfile = "3.20.0"
image = { version = "0.25.6", optional = true }
jp2k = { path = "jp2k", optional = true }

[build-dependencies]
bindgen = { version = "0.69", optional = true }
clang-sys = { version = "1.8", optional = true }

[features]
jp2k = ["dep:jp2k", "bindgen", "clang-sys", "image", "jp2k/jp2k"]
